### ISSUE TITLE
Visiting foods.html

### ISSUE THREAD

**Issue by jayphodges** [rickyamparo/quantified-self#1]
If I visit foods.html, I should see a table of all my foods, with Name, Calories and a delete icon for each food

**Comment by rickyamparo** [comment]
I created a Mock table on the food html page, need to make API calls to the backend to pull accurate food information.

**Comment by rickyamparo** [comment]
Working on getting the first Ajax call to the backend working. Running into a weird error where jquery is not defined, trying to config webpack to call jquery
